# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2016-12-10 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('qq', models.CharField(max_length=11)),
                ('telphone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=1024)),
                ('park', models.CharField(max_length=1024)),
                ('hosenumber', models.CharField(max_length=1024)),
                ('hosesize', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
